---
#kiosk_url: "http://vesta:8123/dashboard-homelab/0?kiosk"
kiosk_url: "http://grafana.lab.local/d/minirack-cluster-resources/minirack-cluster-resources?orgId=1&from=now-15m&to=now&timezone=utc&var-datasource=default&var-cluster=&refresh=5s&editIndex=0&kiosk=true"