#SPDX-License-Identifier: MIT-0
---
ssh:
  disable_password_login: false
  disable_root_ssh: true

  user:
    name: admin
    groups:
      - sudo
    
  

  
  

# SSH config & services
sshd: 
  config_path: "/etc/ssh/sshd_config"
  service_names:
    - "sshd"
    - "ssh"