---
- name: Validate variables
  ansible.builtin.assert:
    that:
      - ssh_local_key_path is defined
      - ssh_local_pubkey_path is defined
      - ansible_ssh_user is defined
    fail_msg: >
      Missing networking vars for {{ inventory_hostname }}.
      Expected: ansible_ssh_user, ssh_local_key_path, ssh_local_pubkey_path

- name: Ensure local SSH directory exists
  ansible.builtin.file:
    path: "{{ ssh_local_key_path | expanduser | dirname }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  run_once: true

- name: Copy SSH private key
  ansible.builtin.copy:
    src: files/id_ed25519
    dest: "{{ ssh_local_key_path | expanduser }}"
    mode: "0600"
  delegate_to: localhost
  run_once: true

- name: Copy SSH public key
  ansible.builtin.copy:
    src: files/id_ed25519.pub
    dest: "{{ ssh_local_pubkey_path | expanduser }}"
    mode: "0644"
  delegate_to: localhost
  run_once: true

- name: Ensure local public key exists on control node
  ansible.builtin.stat:
    path: "{{ ssh_local_pubkey_path | expanduser }}"
  register: pubkey_stat
  delegate_to: localhost
  run_once: true

- name: Fail if local public key is missing
  ansible.builtin.fail:
    msg: "Public key not found at {{ ssh_local_pubkey_path | expanduser }} on the control machine."
  when: not pubkey_stat.stat.exists
  delegate_to: localhost
  run_once: true