---
- name: Validate variables
  ansible.builtin.assert:
    that:
      - ssh.local_key_path is defined
      - ssh.local_pubkey_path is defined
      - ssh.user is defined
    fail_msg: >
      Missing networking vars for {{ inventory_hostname }}.
      Expected: ssh.user, ssh.local_key_path, ssh.local_pubkey_path


- name: Ensure ~/.ssh exists
  ansible.builtin.file:
      path: "~/.ssh"
      state: directory
      mode: "0700"
  delegate_to: localhost

- name: Copy SSH private key
  ansible.builtin.copy:
    src: files/id_ed25519
    dest: "~/.ssh/id_ed25519"
    mode: "0600"
  delegate_to: localhost

- name: Copy SSH public key
  ansible.builtin.copy:
    src: files/id_ed25519.pub
    dest: "~/.ssh/id_ed25519.pub"
    mode: "0644"
  delegate_to: localhost

- name: Ensure local public key exists on control node
  ansible.builtin.stat:
    path: "{{ ssh.local_pubkey_path | expanduser }}"
  register: pubkey_stat
  delegate_to: localhost
  run_once: true

- name: Fail if local public key is missing
  ansible.builtin.fail:
    msg: "Public key not found at {{ ssh.local_pubkey_path }} on the control machine."
  when: not pubkey_stat.stat.exists
  delegate_to: localhost
  run_once: true