---
- name: ARGOCD | Create argocd namespace
  delegate_to: localhost
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present
    kubeconfig: "{{ kubeconfig }}"
  
- name: ARGOCD | Install ArgoCD
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    namespace: argocd
    kubeconfig: "{{ kubeconfig }}"

- name: ARGOCD | Wait for ArgoCD server
  delegate_to: localhost
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: argocd
    label_selectors:
      - app.kubernetes.io/name=argocd-server
    kubeconfig: "{{ kubeconfig }}"
  register: argocd_pods
  retries: 30
  delay: 10
  until: argocd_pods.resources | length > 0

- name: ARGOCD | Wait until all ArgoCD pods are Ready
  ansible.builtin.command:
    cmd: kubectl --kubeconfig {{ kubeconfig }} wait --for=condition=Ready pod --all -n argocd --timeout=600s
  delegate_to: localhost
  run_once: true
  changed_when: false