#SPDX-License-Identifier: MIT-0
---
- name: Install ArgoCD
  import_tasks: install-argocd.yml
  when: inventory_hostname == groups['masters'][0]
  run_once: true
  tags:
    - argocd

- name: Bootstrap ArgoCD with applications
  import_tasks: bootstrap-cluster.yml
  when: inventory_hostname == groups['masters'][0]
  run_once: true
  tags:
    - argocd