#SPDX-License-Identifier: MIT-0
---
- name: Configure Wired Networking
  import_tasks: wired.yml
  tags:
    - networking

- name: Configure dns
  import_tasks: install-mdns.yml
  tags:
    - networking
    - dns