#SPDX-License-Identifier: MIT-0
---
- name: Configure Wired Networking
  import_tasks: wired.yml
  tags:
    - networking

- name: Configure WiFi
  import_tasks: wifi.yml
  when: disable_wifi | default(false)
  tags:
    - networking