# SPDX-License-Identifier: MIT-0
---
- name: Enable cgroup on all nodes
  import_tasks: enable-cgroup.yml
  tags:
    - cgroup

- name: Install Longhorn storage prerequisites on all nodes
  import_tasks: install-storage-prereqs.yml
  tags:
    - storage
    - longhorn

- name: Install the master nodes
  import_tasks: install-master-nodes.yml
  when: "'masters' in group_names"
  tags:
    - k3s
    - masters

- name: Configure the master nodes
  import_tasks: configure-master.yml
  when: "'masters' in group_names"
  tags:
    - k3s
    - masters

- name: Install and Configure the worker nodes
  import_tasks: install-worker-nodes.yml
  when: "'workers' in group_names"
  tags:
    - k3s
    - workers

- name: Uninstall k3s
  import_tasks: uninstall.yml
  when: "'k3s-cleanup' in ansible_run_tags"
  tags:
    - k3s-cleanup