version: 3

images:
  base_image:
    name: docker.io/redhat/ubi9:9.7

dependencies:
  python_interpreter:
    package_system: python3
  
  ansible_core:
    package_pip: ansible-core
  
  ansible_runner:
    package_pip: ansible-runner
  
  system: bindep.txt
  
  python: requirements.txt

  galaxy: requirements.yml
  
additional_build_steps:
  append_final:
    - RUN curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    - RUN install -m 0755 kubectl /usr/local/bin/kubectl
    - RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - RUN curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
    - RUN chmod +x /usr/local/bin/yq

