
---

- name: Set Cluster API Server address for kubeconfig
  set_fact:
    cluster_api_server: "{{ hostvars[groups['masters'][0]].ansible_host | default(groups['masters'][0], true) }}"

- name: Read k3s kubeconfig (rancher/k3s.yaml) into fact
  become: true
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_kubeconfig_raw

- name: Set kubeconfig fact (decoded)
  ansible.builtin.set_fact:
    k3s_kubeconfig: "{{ k3s_kubeconfig_raw.content | b64decode }}"

- name: Replace localhost with first master
  set_fact:
    kubeconfig_raw: >-
      {{ k3s_kubeconfig |
         regex_replace('https://127.0.0.1:6443',
                       'https://' + cluster_api_server + ':6443') }}

- name: Ensure kube directory exists on controller
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{kubeconfig | dirname}}"
    state: directory
    mode: "0700"

- name: K3S | Write kubeconfig
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{ kubeconfig }}"
    content: "{{ kubeconfig_raw }}"
    mode: "0600"