#SPDX-License-Identifier: MIT-0
---
- name: prepare local host
  import_tasks: get-kubeconfig.yml
  when: inventory_hostname == groups['masters'][0]
  run_once: true
  tags:
    - k3s
    - k3s-client