- name: K3S | Wait for API
  command: kubectl --kubeconfig {{kubeconfig}} get nodes
  delegate_to: localhost
  register: api_check
  retries: 3
  delay: 10
  until: api_check.rc == 0
  changed_when: false
  failed_when: api_check.rc != 0 and api_check.attempts | default(1) >= 20

- name: K3S | Verify nodes Ready
  shell: |
    kubectl get nodes --kubeconfig {{kubeconfig}} --no-headers | awk '{print $2}'
  register: node_states
  changed_when: false
  delegate_to: localhost

- name: K3S |Fail if node not ready
  fail:
    msg: "Cluster nodes not Ready"
  when: "'NotReady' in node_states.stdout"